export const INDIAN_CITIES = [
  'Agartala', 'Agra', 'Ahmedabad', 'Ahmednagar', 'Aizawl', 'Ajmer', 'Aligarh', 'Allahabad',
  'Ambala', 'Amravati', 'Amritsar', 'Anand', 'Anantapur', 'Asansol', 'Aurangabad', 'Bareilly',
  'Bathinda', 'Belagavi', 'Bengaluru', 'Bhagalpur', 'Bhavnagar', 'Bhilai', 'Bhopal', 'Bhubaneswar',
  'Bikaner', 'Bilaspur', 'Bokaro', 'Chandigarh', 'Chennai', 'Coimbatore', 'Cuttack', 'Davanagere',
  'Dehradun', 'Delhi', 'Dhanbad', 'Dharwad', 'Dibrugarh', 'Durgapur', 'Erode', 'Faridabad',
  'Firozabad', 'Gangtok', 'Gaya', 'Ghaziabad', 'Gorakhpur', 'Gulbarga', 'Guntur', 'Gurugram',
  'Guwahati', 'Gwalior', 'Haridwar', 'Howrah', 'Hubli', 'Hyderabad', 'Imphal', 'Indore',
  'Itanagar', 'Jabalpur', 'Jaipur', 'Jalandhar', 'Jalgaon', 'Jammu', 'Jamnagar', 'Jamshedpur',
  'Jhansi', 'Jodhpur', 'Junagadh', 'Kakinada', 'Kannur', 'Kanpur', 'Karimnagar', 'Karnal',
  'Kochi', 'Kolhapur', 'Kolkata', 'Kollam', 'Kota', 'Kozhikode', 'Kurnool', 'Latur',
  'Lucknow', 'Ludhiana', 'Madurai', 'Malegaon', 'Mangaluru', 'Mathura', 'Meerut', 'Moradabad',
  'Mumbai', 'Muzaffarnagar', 'Muzaffarpur', 'Mysuru', 'Nagpur', 'Nanded', 'Nashik', 'Navi Mumbai',
  'Nellore', 'New Delhi', 'Nizamabad', 'Noida', 'Panaji', 'Panchkula', 'Panipat', 'Patna',
  'Pondicherry', 'Pune', 'Raipur', 'Rajkot', 'Rajahmundry', 'Ranchi', 'Rourkela', 'Saharanpur',
  'Salem', 'Sangli', 'Shimla', 'Shillong', 'Siliguri', 'Solapur', 'Sonipat', 'Srinagar',
  'Surat', 'Thane', 'Thanjavur', 'Thiruvananthapuram', 'Thrissur', 'Tiruchirappalli', 'Tirunelveli',
  'Tirupati', 'Tiruppur', 'Tumkur', 'Udaipur', 'Ujjain', 'Vadodara', 'Varanasi', 'Vellore',
  'Vijayawada', 'Visakhapatnam', 'Warangal',
];
